

options_for_training=pure_train_optionset('Epochs', 1000, ...
'Inhibitory','true', ...
'Excitatory','true', ...
'Inhibitory_function','tansig', ...
'Excitatory_function','tansig', ...
'Inhibitory_momentum',0.02, ...
'Excitatory_momentum',0.02, ...
'Inhibitory_momentum_degradation',0, ...
'Excitatory_momentum_degradation',0, ...
'Inhibitory_learning_rate',0.03, ...
'Excitatory_learning_rate',0.03, ...
'Target_success',0.95, ...
'Randomize_batch','true', ...
'Renew_weights','true',...
'Epochs_for_renewal',10,...
'Report','false');

disp('Testing logic gates networks')
izknet_options=izknet_optionset('Initialization','mixed');
net_XOR=izknet([2 2],izknet_options);

net_XOR=pure_train_izknet(net_XOR,[0 1 1 0;1 0 1 0],[1 1 0 0;0 0 1 1],options_for_training);

net_AND=init_izkn([2 2]);

net_AND=pure_train_izknet(net_AND,[0 1 1 0;1 0 1 0],[0 0 1 0;1 1 0 1],options_for_training);

net_OR=init_izkn([2 2]);

net_OR=pure_train_izknet(net_OR,[0 1 1 0;1 0 1 0],[1 1 1 0;0 0 0 1],options_for_training);

net_NAND=init_izkn([2 2]);

net_NAND=pure_train_izknet(net_NAND,[0 1 1 0;1 0 1 0],[1 1 0 1;0 0 1 0],options_for_training);

net_NOR=init_izkn([2 2]);

net_NOR=pure_train_izknet(net_NOR,[0 1 1 0;1 0 1 0],[0 0 0 1;1 1 1 0],options_for_training);

net_XNOR=init_izkn([2 2]);

net_XNOR=pure_train_izknet(net_XNOR,[0 1 1 0;1 0 1 0],[0 0 1 1;1 1 0 0],options_for_training);

