function net=izknet(layers,options)

if nargin<2
   options=izknet_optionset(); 
end

net=init_izkn(layers,options.Type,options.Purpose,options.ms,...
    options.Cost_matrix,options.a,options.b,options.c,options.d,...
    options.Amplifier,options.Voltage_sent,options.Number_of_inputs,...
    options.Number_of_outputs,options.Std_constant,...
    options.Regression_matrix,options.Output_layer,...
    options.Sensor_ranges,options.Sensor_neurons_distribution,options.Initialization,...
    options.k);

end