function options=pure_train_optionset_final(varargin)


options=struct('Epochs', 100, ...
'Inhibitory','true', ...
'Excitatory','true', ...
'Inhibitory_function','purelin', ...
'Excitatory_function','purelin', ...
'Inhibitory_momentum',0.1, ...
'Excitatory_momentum',0.1, ...
'Inhibitory_momentum_degradation',0, ...
'Excitatory_momentum_degradation',0, ...
'Inhibitory_learning_rate',0, ...
'Excitatory_learning_rate',0, ...
'Target_success',0.94, ...
'Randomize_batch','true', ...
'Renew_weights','false',...
'Epochs_for_renewal',3,...
'Discrepancy_inhibition',0,...
'Discrepancy_excitation',1,...
'Discrepancy_inhibition_degradation',1,...
'Discrepancy_excitation_degradation',0,...
'Report','true');


i=1;
while i<nargin   
   options.(varargin{i})=varargin{i+1};
   i=i+2; 
end

end

