function net=knet(layers,options)

if nargin<2
   options=knet_optionset(); 
end

net=init_kn(layers,options.Type,options.Purpose,options.a,...
    options.Number_of_inputs,options.ms,...
    options.Number_of_outputs,options.Std_constant,...
    options.Regression_matrix,options.Output_layer,options.Sensor_ranges,...
    options.Sensor_neurons_distribution,options.Amplifier,...
    options.Cost_matrix);

end