function options=izknet_optionset(varargin)



options=struct('Type','feedforward',...
    'Purpose','classification',...
    'ms',20,...
    'Cost_matrix',[1 1 1 1],...
    'a',0.045,...
    'b',0.2,...
    'c',-65,...
    'd',5,...
    'Amplifier',30,...
    'Voltage_sent',60,...
    'Sensor_ranges',[],...
    'Std_constant',2.5,...
    'Regression_matrix',[],...
    'Output_layer',[],...
    'Number_of_inputs',1,...
    'Number_of_outputs',1,...
    'Sensor_neurons_distribution',[],...
    'Initialization','positive/negative',...
    'k',1);


i=1;
while i<nargin 
   options.(varargin{i})=varargin{i+1};
   i=i+2; 
end


end