function options=pure_train_optionset_final(varargin)


options=struct('Epochs', 100, ...
'Inhibitory_momentum',0.1, ...
'Excitatory_momentum',0.1, ...
'Target_success',0.9, ...
'Randomize_batch','false',...
'Renew_weights','true',...
'Epochs_for_renewal',10, ...
'Report','true');


i=1;
while i<nargin   
   options.(varargin{i})=varargin{i+1};
   i=i+2; 
end

end

